### ISSUE TITLE
Idea: make options appear as disabled/readonly

### ISSUE THREAD

**Issue by smeedijzer-internet** [soberwp/intervention#46]
What do you think about making the options appear as disabled/readonly instead of removing them?

Like this plugin:
https://github.com/devgeniem/wp-readonly-options

**Comment by darrenjacoby** [comment]
Hey @smeedijzer-internet , I thought of this when building it. 

I still like the idea, perhaps even preferring it to removing the field to be honest. I would like to get others thoughts on this too. If I am to offer both, do you have a suggestion for the config file API to alternate between removing/read-only?

**Comment by darrenjacoby** [comment]
@smeedijzer-internet [FYI](https://twitter.com/withjacoby/status/1354795352147300362)

**Comment by darrenjacoby** [comment]
I tested changing the fields to disabled and it feels much better, so application options now disabled fields rather than removing. You can still use `wp-admin` to remove the fields for all or specific roles.

Thanks for the suggestion @smeedijzer-internet 

#https://github.com/soberwp/intervention/commit/89cbe45aaa5dc788f881023194f47a5de205ed70

**Comment by smeedijzer-internet** [comment]
Awesome, going to test it tomorrow!

**Comment by smeedijzer-internet** [comment]
Tested it, and it works perfect! thanks
